### ISSUE TITLE
如何在QQ群中指定 Target 对象？

### ISSUE THREAD

**Issue by ChocoFleece** [idranme/koishi-plugin-rua#1]
如何在QQ群中指定 Target 对象？
使用<@昵称>的形式并不有效，在QQ群聊中仅能对自己生效

在QQ群中，@用户的行为，Bot会接收到的消息为：

<at id="QQ号"/>

希望作者有精力的话能够适配下！

**Comment by idranme** [comment]
格式：
rua -t @对方

**Comment by Inaba26** [comment]
> 格式： rua -t @对方

目前的版本中，我使用 rua -t @对方，依然会将对象指向自己...
使用 --target 也是如此，但是并不会提示我 “选项 target 输入无效，请指定正确的用户。”

**Comment by idranme** [comment]
> > 格式： rua -t @对方
> 
> 目前的版本中，我使用 rua -t @对方，依然会将对象指向自己...
> 使用 --target 也是如此，但是并不会提示我 “选项 target 输入无效，请指定正确的用户。”

你用了哪个 onebot 实现端？

**Comment by Inaba26** [comment]
> > > 格式： rua -t @对方
> > 
> > 
> > 目前的版本中，我使用 rua -t @对方，依然会将对象指向自己...
> > 使用 --target 也是如此，但是并不会提示我 “选项 target 输入无效，请指定正确的用户。”
> 
> 你用了哪个 onebot 实现端？

我使用了 https://github.com/NapNeko/NapCatQQ 中的 反向 WebSocket 服务，我第一次使用 Koishi 是参考的 B站教程，我的 adapter 分组中只有相关的插件应该 adapter-onebot 是启用状态，其中 protocol 项为 ws-reverse

**Comment by idranme** [comment]
> 我使用了 https://github.com/NapNeko/NapCatQQ 中的 反向 WebSocket 服务，我第一次使用 Koishi 是参考的 B站教程，我的 adapter 分组中只有相关的插件应该 adapter-onebot 是启用状态，其中 protocol 项为 ws-reverse

我用 LLOneBot，没有这个问题
